export const REGION_MAP: Record<string, string> = {
  서울: 'SEOUL',
  경기: 'GYEONGGI',
  인천: 'INCHEON',
  부산: 'BUSAN',
  대구: 'DAEGU',
  광주: 'GWANGJU',
  대전: 'DAEJEON',
  울산: 'ULSAN',
  세종: 'SEJONG',
  강원: 'GANGWON',
  경남: 'GYEONGNAM',
  경북: 'GYEONGBUK',
  전남: 'JEONNAM',
  전북: 'JEONBUK',
  충남: 'CHUNGNAM',
  충북: 'CHUNGBUK',
  제주: 'JEJU',
  해외: 'OVERSEAS',
  기타: 'OTHERS',
};
