export const SCHOOL_MAP: Record<string, string> = {
  서울대학교: 'SEOUL',
  연세대학교: 'YEONSEI',
  고려대학교: 'KOREA',
  서강대학교: 'SOGANG',
  성균관대학교: 'SUNGKYUNKWAN',
  한양대학교: 'HANYANG',
  이화여자대학교: 'EWHA',
  중앙대학교: 'CHUNGANG',
  경희대학교: 'KYUNGHEE',
  한국외대: 'HUFS',
  서울시립대학교: 'UNIVERSITY_OF_SEOUL',
  건국대학교: 'KONKUK',
  동국대학교: 'DONGGUK',
  홍익대학교: 'HONGIK',
  숙명여자대학교: 'SOOKMYUNG',
  국민대학교: 'KOOKMIN',
  숭실대학교: 'SOONGSIL',
  세종대학교: 'SEJONG',
  단국대학교: 'DANKOOK',
  '한양대학교 ERICA': 'HANYANG_ERICA',
  광운대학교: 'KWANGWOON',
  명지대학교: 'MYEONGJI',
  상명대학교: 'SANGMYUNG',
  가톨릭대학교: 'CATHOLIC',
  성신여자대학교: 'SUNGSHIN',
  인천대학교: 'INCHEON',
  가천대학교: 'GACHON',
  경기대학교: 'KYONGGI',
};
